version: '3'
services:
  gh-proxy:
    container_name: gh-proxy
    build:
      context: .
    image: gh-proxy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/githubproxy
      - LOGSTASH_HOST=logstash
    ports:
      - "8080:8080"
    networks:
      - default
      - elk-network
    depends_on:
      - db

  db:
    image: postgres
    container_name: gh-proxy-db
    environment:
      - POSTGRES_DB=githubproxy
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=demo@example.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  es_data:
  local_pgdata:
  pgadmin-data:

networks:
  default:
  elk-network:
    external: true