spring.application.name=github-proxy
app.githubClient.url=https://api.github.com/repos
spring.datasource.url=jdbc:postgresql://localhost:5432/githubproxy
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.cloud.openfeign.circuitbreaker.enabled=true